// Generated by CoffeeScript 1.7.1

/*
argv = require('optimist')
    .usage('Start stormbolt with a configuration file.\nUsage: $0')
    .demand('f')
    .default('f','/etc/stormstack/stormbolt.json')
    .alias('f', 'file')
    .describe('f', 'location of bolt configuration file')
    .argv
config = ''
fileops = require("fileops")
res =  fileops.fileExistsSync argv.file
unless res instanceof Error
    boltContent = fileops.readFileSync argv.file
    config = JSON.parse boltContent
else
    return new Error "file does not exist! " + res
 */

(function() {
  var bolt, stormbolt;

  stormbolt = require('./bolt');

  bolt = new stormbolt;

  bolt.run(function(res) {
    if (res instanceof Error) {
      return console.log('error: ' + res);
    }
  });

}).call(this);
