// Generated by CoffeeScript 1.7.1

/*
argv = require('optimist')
    .usage('Start stormbolt with a configuration file.\nUsage: $0')
    .demand('f')
    .default('f','/etc/stormstack/stormbolt.json')
    .alias('f', 'file')
    .describe('f', 'location of bolt configuration file')
    .argv
config = null
fileops = require("fileops")
res =  fileops.fileExistsSync argv.file
unless res instanceof Error
    boltContent = fileops.readFileSync argv.file
    config = JSON.parse boltContent
else
    return new Error "file does not exist! " + res
 */

(function() {
  var StormBolt, agent, storm;

  storm = null;

  StormBolt = require('./bolt');

  agent = new StormBolt;

  agent.run();

}).call(this);
