// Generated by CoffeeScript 1.7.1
(function() {
  this.include = function() {
    var agent;
    agent = this.settings.agent;
    this.get({
      '/clients': function() {
        return this.send(agent.clients.list());
      }
    });
    return this.get({
      '/clients/:id': function() {
        var match;
        match = agent.clients.get(this.params.id);
        if (match != null) {
          return this.send(match);
        } else {
          return this.send(404);
        }
      }
    });
  };

}).call(this);
