// Generated by CoffeeScript 1.7.1
(function() {
  this.include = function() {
    var agent;
    agent = this.settings.agent;
    this.get({
      '/clients': function() {
        return this.send(agent.clients.list());
      }
    });
    this.get({
      '/clients/:id': function() {
        var match;
        match = agent.clients.get(this.params.id);
        if (match != null) {
          return this.send(match);
        } else {
          return this.send(404);
        }
      }
    });
    return this.all({
      '/proxy/:id/*': function() {
        var bolt;
        bolt = agent.clients.entries[this.params.id];
        if ((bolt != null) && (bolt.relay != null)) {
          this.req.target = 8000;
          this.req.url = this.params[0];
          return bolt.relay(this.req, this.res);
        } else {
          return this.send(404);
        }
      }
    });
  };

}).call(this);
